### ISSUE TITLE
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'

### ISSUE THREAD

**Issue by farynaio** [VARIANTE/generator-vars-django#2]
I got this when performing build command 'gulp':

[22:35:19] Starting 'build'...
Traceback (most recent call last):
  File "/Volumes/Private_dev_own/lnpp/app/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/**init**.py", line 18, in setup
    from django.utils.log import configure_logging
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/utils/log.py", line 10, in <module>
    from django.views.debug import ExceptionReporter, get_exception_reporter_filter
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/views/debug.py", line 10, in <module>
    from django.http import (HttpResponse, HttpResponseServerError,
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/http/**init**.py", line 4, in <module>
    from django.http.response import (HttpResponse, StreamingHttpResponse,
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/http/response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/core/serializers/**init**.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/core/serializers/base.py", line 6, in <module>
    from django.db import models
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/db/models/**init**.py", line 6, in <module>
    from django.db.models.query import Q, QuerySet, Prefetch  # NOQA
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/db/models/query.py", line 13, in <module>
    from django.db.models.fields import AutoField, Empty
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/db/models/fields/**init**.py", line 18, in <module>
    from django import forms
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/forms/**init**.py", line 6, in <module>
    from django.forms.fields import \*  # NOQA
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/forms/fields.py", line 18, in <module>
    from django.forms.utils import from_current_timezone, to_current_timezone
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/forms/utils.py", line 15, in <module>
    from django.utils.html import format_html, format_html_join, escape
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/utils/html.py", line 16, in <module>
    from .html_parser import HTMLParser, HTMLParseError
  File "/Users/devil/.virtualenvs/lnpp/lib/python3.5/site-packages/django/utils/html_parser.py", line 12, in <module>
    HTMLParseError = _html_parser.HTMLParseError
AttributeError: module 'html.parser' has no attribute 'HTMLParseError'

**Comment by andrewscwei** [comment]
Hey Adam, thanks for the report. It appears that you are using Python 3.5, which I believe there was a known issue using Django 1.7 with your version of Python (see [this report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800137;msg=32) for details). Either upgrading Django to a later version or downgrading Python should fix your issue.

**Comment by farynaio** [comment]
Hi Andrew,

thanks for fast answer. I switched to Django 1.9 and it works. I found one more issue, on 'gulp serve' server starts at port 3000 but browser opens page at 9000.

**Comment by andrewscwei** [comment]
Adam,

That is intended. What's happening is Django runs its server at port 3000 and BrowserSync runs as a proxy at 9000. You can view your app in either, but with BrowserSync running at port 9000 you get live reload features as you make changes. During development I recommend running `gulp --d --w --s`, which builds your project in debug, serves it and watches for ongoing file changes, all in one go. For more info on what the flags mean you can refer to `gulpfile.js` which should point you to `.taskconfig`. Please be warned that BrowserSync might get stuck on the first time around, so you might have to do a manual browser refresh (just this one time) :).

**Comment by Teatoller** [comment]
Hey, 
Thank you for posting this issue, I had a similar challenge and update to Django version 2.1.2 and the matter got resolved.
