### ISSUE TITLE
Generator failing

### ISSUE THREAD

**Issue by muminoff** [VARIANTE/generator-vars-django#4]
```
$ yo django-webapp
...
I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN deprecated find-file@0.1.4: Use the globby package instead

> pngquant-bin@0.1.7 postinstall /Users/sardor/Projects/yayma/etc/node_modules/pngquant-bin
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { name: 'pngquant',
  url: 'https://raw.github.com/sindresorhus/node-pngquant-bin/v0.1.7/vendor/osx/pngquant' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/sardor/Projects/yayma/etc/node_modules/download/index.js:35:43
    at each (/Users/sardor/Projects/yayma/etc/node_modules/each-async/each-async.js:63:4)
    at module.exports (/Users/sardor/Projects/yayma/etc/node_modules/download/index.js:33:5)
    at BinWrapper._download (/Users/sardor/Projects/yayma/etc/node_modules/pngquant-bin/node_modules/bin-wrapper/index.js:283:14)
    at BinWrapper.check (/Users/sardor/Projects/yayma/etc/node_modules/pngquant-bin/node_modules/bin-wrapper/index.js:75:10)
    at /Users/sardor/Projects/yayma/etc/node_modules/pngquant-bin/index.js:27:5
    at FSReqWrap.cb [as oncomplete] (fs.js:251:19)
yayma@0.0.0 /Users/sardor/Projects/yayma/etc
└── (empty)

npm WARN yayma@0.0.0 No description
npm WARN yayma@0.0.0 No repository field.
npm WARN yayma@0.0.0 No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/sardor/.nvm/versions/node/v6.0.0/bin/node" "/Users/sardor/.nvm/versions/node/v6.0.0/bin/npm" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! pngquant-bin@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@0.1.7 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pngquant-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pngquant-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pngquant-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sardor/Projects/yayma/etc/npm-debug.log
npm ERR! code 1
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (1)
    at Appgenerator.emit (events.js:163:17)
    at done (/Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/yeoman-generator/lib/base.js:318:16)
    at /Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/async/lib/async.js:232:13
    at /Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/async/lib/async.js:113:21
    at /Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/async/lib/async.js:24:16
    at /Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/async/lib/async.js:229:17
    at /Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/async/lib/async.js:516:34
    at Appgenerator.<anonymous> (/Users/sardor/.nvm/versions/node/v6.0.0/lib/node_modules/generator-django-webapp/node_modules/yeoman-generator/lib/actions/install.js:43:7)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
```

Node version:

```
$ node --version
v6.0.0
```

NPM version

```
$ npm --version
3.8.6
```

**Comment by andrewscwei** [comment]
`$ yo django-webapp`

It doesn't seem like you are using this generator (`generator-vars-django`)?

**Comment by muminoff** [comment]
Whoops, sorry I seem to be confused..
