### ISSUE TITLE
Path to virtualenv

### ISSUE THREAD

**Issue by jakobadam** [VARIANTE/generator-vars-django#5]
Got the following error 

```
Successfully installed Django ecdsa paramiko pycrypto
Cleaning up...
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/jakob/projects/foobar/bin/activate'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at readFileAsString (/usr/lib/node_modules/generator-vars-django/node_modules/yeoman-generator/lib/actions/wiring.js:277:13)
    at null.<anonymous> (/usr/lib/node_modules/generator-vars-django/app/index.js:280:29)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

In https://github.com/VARIANTE/generator-vars-django/blob/master/app/index.js#L279 the path to bin/activate seems wrong to me.

Unless you make a symlink in the project dir to bin

```
ln -s {...}/env/bin bin 
```

kind regards,
Jakob

**Comment by andrewscwei** [comment]
Hey thanks for the report. The generator naively assumes that the virtual environment path is the project root, hence it's looking for `{project_root}/bin/activate`. Not too smart I agree :). I'm adding some updates to the generator at the moment (upgrading to Django 1.9 and such) and the next update will  check for `process.env.VIRTUAL_ENV` instead.

**Comment by andrewscwei** [comment]
It now checks for `process.env.VIRTUAL_ENV` starting from 5730c07a8fe1d6787415bef1068002531866a63a.

**Comment by jakobadam** [comment]
Awesome:)
