### ISSUE TITLE
Undefined variable in build.js

### ISSUE THREAD

**Issue by jakobadam** [VARIANTE/generator-vars-django#6]
```
/home/jakob/projects/op/tasks/build.js:60
      if (shouldWatch) {
          ^

ReferenceError: shouldWatch is not defined
    at DestroyableTransform.<anonymous> (/home/jakob/projects/op/tasks/build.js:60:11)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:188:7)
    at onwriteError (/home/jakob/projects/op/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:10)
    at onwrite (/home/jakob/projects/op/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:339:11)
    at WritableState.onwrite (/home/jakob/projects/op/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:123:5)
    at afterTransform (/home/jakob/projects/op/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:81:3)
    at TransformState.afterTransform (/home/jakob/projects/op/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at errorM (/home/jakob/projects/op/node_modules/gulp-sass/index.js:134:14)
    at Object.callback (/home/jakob/projects/op/node_modules/gulp-sass/index.js:145:18)
```

**Comment by andrewscwei** [comment]
Thanks for report. Both this and #7 are now fixed in v3.0.4.
