### ISSUE TITLE
util is undefined build.js

### ISSUE THREAD

**Issue by jakobadam** [VARIANTE/generator-vars-django#7]
```
/home/jakob/projects/op/tasks/build.js:104
        util.log(util.colors.blue('[browserify]'), util.colors.red(`Error: ${err.message}`));
        ^

ReferenceError: util is not defined
    at Readable.<anonymous> (/home/jakob/projects/op/tasks/build.js:104:9)
    at emitOne (events.js:101:20)
    at Readable.emit (events.js:188:7)
    at Labeled.<anonymous> (/home/jakob/projects/op/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:96:13)
    at Labeled.emit (events.js:188:7)
    at Labeled.<anonymous> (/home/jakob/projects/op/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:101:20)
    at Labeled.emit (events.js:188:7)
    at Deps.<anonymous> (/home/jakob/projects/op/node_modules/stream-splicer/index.js:130:18)
```

Should be $util.

**Comment by andrewscwei** [comment]
Thanks for report. Both this and #6 are now fixed in v3.0.4.
